# Generated by Django 5.0.1 on 2024-01-14 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Curso', '0002_categoria_proveedor_remove_curso_profesor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Curso.proveedor'),
        ),
    ]
